// SPDX-License-Identifier: GPL-3.0-only
//
// Copyright (C) 2026 fx991-rs contributors
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 3.  It is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License in LICENSE for more details.

//! Differential test: render the ROM from memory, compare against the listing.
//!
//! `data/_disas_verF.txt` was generated by a separate tool from its own
//! instruction-set chart.  Comparing this decoder against it is a
//! far stronger check than either one alone: the two share no code, so a
//! disagreement means at least one of them is wrong about the encoding.
//!
//! The comparison normalizes whitespace, because the listing's operand column
//! alignment is a formatting choice of the generator and not part of the
//! instruction's meaning.
//!
//! Both inputs are copyrighted or large, so the test skips when `data/` is
//! absent rather than failing -- the same convention as the rest of the
//! workspace.

use nxu8_asm::disasm::{disassemble_one, InsnKind, SliceReader};

/// Where the ROM and listing live, relative to the workspace root.
fn workspace_root() -> Option<std::path::PathBuf> {
    let mut dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    loop {
        if dir.join("data").is_dir() {
            return Some(dir);
        }
        if !dir.pop() {
            return None;
        }
    }
}

struct ListingLine {
    address: u32,
    text: String,
    /// How many bytes the listing gives this instruction.
    bytes: usize,
}

/// Parse the listing's `ADDR  BYTES  TEXT` lines.
///
/// The byte field ends at the first run of two spaces, so a mnemonic like `BC`
/// -- which is valid hex -- is not mistaken for a byte.
fn parse_listing(text: &str) -> Vec<ListingLine> {
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim_end();
        if line.len() < 9 {
            continue;
        }
        let Ok(address) = u32::from_str_radix(&line[..6], 16) else {
            continue;
        };
        let rest = line[6..].trim_start();
        let Some(split) = rest.find("  ") else {
            continue;
        };
        let bytes = rest[..split].split_whitespace().count();
        let text = rest[split..]
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ");
        out.push(ListingLine {
            address,
            text,
            bytes,
        });
    }
    out
}

/// Collapse whitespace runs so alignment differences do not matter.
fn normalize(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[test]
fn every_listed_instruction_renders_the_same_from_the_rom() {
    let Some(root) = workspace_root() else {
        eprintln!("skipping: data/ is not present");
        return;
    };
    let Ok(text) = std::fs::read_to_string(root.join("data/_disas_verF.txt")) else {
        eprintln!("skipping: data/_disas_verF.txt is not present");
        return;
    };
    let Ok(rom) = std::fs::read(root.join("data/rom_verF.bin")) else {
        eprintln!("skipping: data/rom_verF.bin is not present");
        return;
    };

    let listing = parse_listing(&text);
    assert!(listing.len() > 100_000, "listing looks truncated");

    let mut mismatches: Vec<String> = Vec::new();
    let mut by_kind: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    let mut matched = 0usize;
    let mut checked = 0usize;

    for line in &listing {
        // Only the listing's own claim about a start address is checked: if the
        // generator and this decoder disagree about an instruction's length, the
        // next iteration lands mid-instruction, which is exactly what should fail.
        let offset = line.address as usize;
        if offset + 3 >= rom.len() {
            continue;
        }
        let mut reader = SliceReader::new(&rom, 0);
        let insn = disassemble_one(&mut reader, line.address);
        checked += 1;

        let expected = normalize(&line.text);
        let actual = normalize(&insn.text);
        // The listing's byte column is the generator's claim about the
        // instruction's length, so comparing it catches a disagreement about the
        // long-immediate bit rather than about operand syntax.
        if insn.length != line.bytes && insn.kind != InsnKind::DsrPrefix {
            *by_kind
                .entry(format!("length {} != {}", insn.length, line.bytes))
                .or_insert(0) += 1;
            if mismatches.len() < 60 {
                mismatches.push(format!(
                    "{:06X}: length {} but the listing lists {} bytes",
                    line.address, insn.length, line.bytes
                ));
            }
            continue;
        }
        if expected == actual {
            matched += 1;
        } else {
            // Group by the pair of mnemonic families involved, so one report
            // covers a whole class of encoding bug rather than 40 samples of it.
            let key = format!(
                "{:?} -> {:?}",
                expected.split(' ').next().unwrap_or(""),
                actual.split(' ').next().unwrap_or("")
            );
            *by_kind.entry(key).or_insert(0) += 1;
            if mismatches.len() < 60 {
                mismatches.push(format!(
                    "{:06X}: {:<12} handler {:?}\n      listing {:?}\n      decoder {:?}",
                    line.address,
                    insn.byte_text().trim_end(),
                    insn.handler.unwrap_or("-"),
                    expected,
                    actual
                ));
            }
        }
    }

    let ratio = matched as f64 / checked as f64;
    // Always report, so a silently-skipping test cannot masquerade as a pass.
    eprintln!(
        "oracle: {matched}/{checked} render identically ({:.4}%)",
        ratio * 100.0
    );
    if !mismatches.is_empty() {
        let mut kinds: Vec<_> = by_kind.iter().collect();
        kinds.sort_by(|a, b| b.1.cmp(a.1));
        eprintln!(
            "{} of {} lines disagree ({:.4}% match)",
            checked - matched,
            checked,
            ratio * 100.0
        );
        eprintln!("mismatch classes ({} total):", by_kind.len());
        for (key, count) in kinds.iter().take(40) {
            eprintln!("  {count:6}  {key}");
        }
        eprintln!("--- samples ---");
        for line in &mismatches {
            eprintln!("  {line}");
        }
    }
    // Exact: the renderer reproduces the listing verbatim, so a single
    // disagreement is a bug in one of the two implementations rather than a
    // tolerance to be widened.
    assert_eq!(
        matched, checked,
        "the decoder and the listing disagree; see the report above"
    );
}

#[test]
fn the_loader_agrees_with_the_listing_about_instruction_lengths() {
    let Some(root) = workspace_root() else {
        return;
    };
    let Ok(text) = std::fs::read_to_string(root.join("data/_disas_verF.txt")) else {
        return;
    };
    let Ok(rom) = std::fs::read(root.join("data/rom_verF.bin")) else {
        return;
    };
    let listing = parse_listing(&text);

    let mut reader = SliceReader::new(&rom, 0);
    let mut disagreements = 0usize;
    for line in listing.iter().take(20_000) {
        let offset = line.address as usize;
        if offset + 3 >= rom.len() {
            continue;
        }
        let insn = disassemble_one(&mut reader, line.address);
        // The generator writes two bytes for a short instruction and four for a
        // long one; anything else means the two disagree about the encoding.
        if insn.length != 2 && insn.length != 4 {
            disagreements += 1;
        }
    }
    assert_eq!(disagreements, 0, "instruction lengths outside {{2,4}}");
}

/// A reader over a byte slice, checking the disassembler reads only the bytes it
/// reports as the instruction's length.
#[test]
fn decoding_reads_exactly_the_bytes_it_reports() {
    let program: Vec<u8> = vec![
        0x00, 0x00, // MOV R0,#0
        0x0C, 0xF0, 0x80, 0xD1, // LEA 0D180h
        0x8E, 0xF2, // POP PC
    ];
    let mut reader = SliceReader::new(&program, 0);
    let first = disassemble_one(&mut reader, 0);
    assert_eq!(first.length, 2);
    let second = disassemble_one(&mut reader, 2);
    assert_eq!(second.length, 4);
    let third = disassemble_one(&mut reader, 6);
    assert_eq!(third.length, 2);
}

/// A `DSR<-` prefix is one executed step together with what follows it, even
/// though the two decode as separate instructions.
#[test]
fn a_dsr_prefix_and_its_payload_are_one_step() {
    // `DSR<- 00h` then `MOV R1,#2`, then a lone `RT`.
    let program: Vec<u8> = vec![0x00, 0xE3, 0x02, 0x01, 0x1F, 0xFE];
    let mut reader = SliceReader::new(&program, 0);
    assert_eq!(nxu8_asm::disasm::step_length(&mut reader, 0), 4);

    let prefix = disassemble_one(&mut reader, 0);
    assert_eq!(prefix.kind, InsnKind::DsrPrefix);
    assert_eq!(prefix.text, "DSR<-   000h");
    assert_eq!(prefix.length, 2);

    let payload = disassemble_one(&mut reader, 2);
    assert_eq!(payload.kind, InsnKind::Normal);
    assert_eq!(payload.text, "MOV     R1, #2");
    assert!(!payload.is_call);

    // With no prefix in front of it, a plain instruction is its own step.
    assert_eq!(nxu8_asm::disasm::step_length(&mut reader, 4), 2);
}

/// `BL` is the only instruction that writes the link register, so it is the only
/// one "step over" has to treat as a call.
#[test]
fn only_bl_reports_itself_as_a_call() {
    let program: Vec<u8> = vec![
        0x00, 0xF0, 0x6A, 0x94, // B 00h:0946Ah  -- a jump, not a call
        0x01, 0xF0, 0x6A, 0x94, // BL 00h:0946Ah -- a call
        0x1F, 0xFE, // RT
    ];
    let mut reader = SliceReader::new(&program, 0);
    assert!(!disassemble_one(&mut reader, 0).is_call);
    assert!(disassemble_one(&mut reader, 4).is_call);
    assert!(!disassemble_one(&mut reader, 8).is_call);
}

/// An opcode the table does not map must still produce a line, because a
/// debugger showing "nothing here" is worse than showing that it is unknown.
#[test]
fn an_unmapped_opcode_is_reported_rather_than_skipped() {
    let program: Vec<u8> = vec![0x58, 0x94];
    let mut reader = SliceReader::new(&program, 0);
    let insn = disassemble_one(&mut reader, 0);
    assert!(insn.is_unknown());
    assert_eq!(insn.handler, None);
    assert_eq!(insn.text, "Unrecognized command");
    assert_eq!(insn.length, 2);
}

/// The two encodings the instruction chart defines but the decode table omits
/// are rendered rather than called unrecognized: a ROM that reaches one is doing
/// something this core cannot execute, which is exactly what a debugger should
/// make visible.
#[test]
fn chart_only_encodings_are_named() {
    // `8F 81` is `EXTBW ER8` with disagreeing register fields.
    let program: Vec<u8> = vec![0x8F, 0x81];
    let mut reader = SliceReader::new(&program, 0);
    let extbw = disassemble_one(&mut reader, 0);
    assert_eq!(extbw.kind, InsnKind::ChartOnly);
    assert_eq!(extbw.text, "Wrong format - EXTBW   ER8");

    // `9D CF` at `rom:06A6` is `BC` with condition field 15, which the table
    // stops short of; its displacement lands at `005E2h`.
    let bc_bytes: Vec<u8> = vec![0x9D, 0xCF];
    let mut reader = SliceReader::new(&bc_bytes, 0x06A6);
    let bc = disassemble_one(&mut reader, 0x06A6);
    assert_eq!(bc.kind, InsnKind::ChartOnly);
    assert_eq!(bc.text, "BC      <Unrecognized>, 005E2h");
}

/// Addresses are word-aligned, so a caller that passes an odd address gets the
/// instruction containing it rather than a shifted decode.
#[test]
fn an_odd_address_is_rounded_down_to_the_instruction() {
    // `MOV SP, ER0` is `0A A1`; passing address 3 must land on the instruction at
    // 2 rather than decoding from the middle of its second byte.
    let program: Vec<u8> = vec![0x8E, 0xF2, 0x0A, 0xA1];
    let mut reader = SliceReader::new(&program, 0);
    let insn = disassemble_one(&mut reader, 3);
    assert_eq!(insn.address, 2);
    assert_eq!(insn.text, "MOV     SP, ER0");
}
